<!DOCTYPE html>
<html class="no-js" lang="en-US"> <!--<![endif]--><head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="profile" href="http://gmpg.org/xfn/11">
<title>Chummies &#x2d; Crime is everywhere, get a sidekick!</title>

<meta name="google-site-verification" content="n-dKXMHA-BMJOMEnr-NwA-PZi1B_DQ62iQPRhi6piV4">
<meta name="yandex-verification" content="9eb0ef951414dbda">
<meta name="robots" content="max-snippet:-1,max-image-preview:standard,max-video-preview:-1">
<meta name="description" content="Crime is everywhere, get a sidekick! Join Chummies today and get the sidekick of your dreams. Do you recognize a superhero when you look one in the face?">


<link rel="stylesheet" id="wp-block-library-css" href="/wp-includes/css/dist/block-library/style.min.css?ver=6.0" media="all">
<link rel="stylesheet" id="chld_thm_cfg_ext1-css" href="https://king-web.net/font-awesome/font-awesome-4.7.0/css/all.min.css?ver=6.0" media="all">
<link rel="stylesheet" id="chld_thm_cfg_ext2-css" href="https://king-web.net/font-awesome/font-awesome-5.11.2/css/all.min.css?ver=6.0" media="all">
<link rel="stylesheet" id="chld_thm_cfg_ext3-css" href="https://king-web.net/font-awesome/font-awesome-5.15.4/css/all.min.css?ver=6.0" media="all">
<link rel="stylesheet" id="responsive-style-css" href="https://mythosimprint.com/files/themes/responsive/core/css/style.min.css?ver=4.7.4" media="all">
<link rel="stylesheet" id="icomoon-style-css" href="https://mythosimprint.com/files/themes/responsive/core/css/icomoon/style.min.css?ver=4.7.4" media="all">
<link rel="stylesheet" id="chld_thm_cfg_child-css" href="https://mythosimprint.com/files/themes/responsive_rose-city/style.css?ver=1.0.0.1631220951" media="all">
<link rel="stylesheet" id="font-awesome-5-all-css" href="https://mythosimprint.com/files/plugins/elementor/assets/lib/font-awesome/css/all.min.css?ver=3.6.5" media="all">
<link rel="stylesheet" id="font-awesome-4-shim-css" href="https://mythosimprint.com/files/plugins/elementor/assets/lib/font-awesome/css/v4-shims.min.css?ver=3.6.5" media="all">

<link rel="stylesheet" id="elementor-frontend-css" href="https://mythosimprint.com/files/plugins/elementor/assets/css/frontend-lite.min.css?ver=3.6.5" media="all">

<link rel="icon" href="/wp-content/blogs.dir/10/files/sites/14/2019/06/chummieslogo01.png" sizes="32x32">
<link rel="icon" href="/wp-content/blogs.dir/10/files/sites/14/2019/06/chummieslogo01.png" sizes="192x192">
<link rel="apple-touch-icon" href="/wp-content/blogs.dir/10/files/sites/14/2019/06/chummieslogo01.png">
<meta name="msapplication-TileImage" content="/wp-content/blogs.dir/10/files/sites/14/2019/06/chummieslogo01.png">
<link rel="stylesheet" type="text/css" href="/css/style.css">
</head>
<body class="home page-template page-template-elementor_header_footer page page-id-7 wp-embed-responsive front-page site-header-main-navigation responsive-site-contained responsive-site-style-boxed header-full-width site-header-layout-horizontal site-header-alignment-center site-mobile-header-layout-horizontal site-mobile-header-alignment-center header-widget-alignment-spread header-widget-position-top inline-logo-site-title site-content-header-alignment-center custom-home-page-active sidebar-position-right featured-image-alignment-left title-alignment-left content-alignment-left footer-bar-layout-horizontal footer-widgets-columns-0 scroll-to-top-device-both scroll-to-top-aligmnment-right menu-item-hover-style-none elementor-default elementor-template-full-width elementor-kit-275 elementor-page elementor-page-7" >
</div>
<div class="site hfeed">
<header id="masthead" class="site-header"><div class="container"><div class="row"><nav id="site-navigation" class="main-navigation" aria-label="Main Menu"><h2 class="screen-reader-text">Main Navigation</h2>
<div class="main-navigation-wrapper"> <button class="menu-toggle" aria-controls="header-menu" aria-expanded="false"><i class="icon-bars"></i><span class="hamburger-menu-label"></span><span class="screen-reader-text">Menu</span></button><ul id="header-menu" class="menu">
<li id="menu-item-39" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-home current-menu-item page_item page-item-7 current_page_item menu-item-39"><a href="/" aria-current="page">Home</a></li>
<li id="menu-item-66" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-66"><a href="/members/">Members</a></li>
</ul>
</div></nav></div></div></header><div data-elementor-type="wp-post" data-elementor-id="7" class="elementor elementor-7">
<section class="elementor-section elementor-top-section elementor-element elementor-element-2a9c587 elementor-section-stretched elementor-section-content-bottom elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-id="2a9c587" data-element_type="section" data-settings="{&quot;stretch_section&quot;:&quot;section-stretched&quot;,&quot;background_background&quot;:&quot;classic&quot;}"><div class="elementor-container elementor-column-gap-default">
<div class="elementor-column elementor-col-33 elementor-top-column elementor-element elementor-element-e761183" data-id="e761183" data-element_type="column"><div class="elementor-widget-wrap"></div></div>
<div class="elementor-column elementor-col-66 elementor-top-column elementor-element elementor-element-348b1f7" data-id="348b1f7" data-element_type="column"><div class="elementor-widget-wrap elementor-element-populated">
<div class="elementor-element elementor-element-7efc7e9 elementor-widget elementor-widget-image" data-id="7efc7e9" data-element_type="widget" data-widget_type="image.default"><div class="elementor-widget-container">
<style>/*! elementor - v3.6.5 - 27-04-2022 */
.elementor-widget-image{text-align:center}.elementor-widget-image a{display:inline-block}.elementor-widget-image a img[src$=".svg"]{width:48px}.elementor-widget-image img{vertical-align:middle;display:inline-block}</style>
<img decoding="async" width="530" height="70" src="/wp-content/blogs.dir/10/files/sites/14/2019/06/chummiesLogo.png" class="attachment-full size-full" alt="Chummies Logo" sizes="(max-width: 530px) 100vw, 530px">
</div></div>
<div class="elementor-element elementor-element-09305f9 elementor-widget elementor-widget-text-editor" data-id="09305f9" data-element_type="widget" data-widget_type="text-editor.default"><div class="elementor-widget-container">
<style>/*! elementor - v3.6.5 - 27-04-2022 */
.elementor-widget-text-editor.elementor-drop-cap-view-stacked .elementor-drop-cap{background-color:#818a91;color:#fff}.elementor-widget-text-editor.elementor-drop-cap-view-framed .elementor-drop-cap{color:#818a91;border:3px solid;background-color:transparent}.elementor-widget-text-editor:not(.elementor-drop-cap-view-default) .elementor-drop-cap{margin-top:8px}.elementor-widget-text-editor:not(.elementor-drop-cap-view-default) .elementor-drop-cap-letter{width:1em;height:1em}.elementor-widget-text-editor .elementor-drop-cap{float:left;text-align:center;line-height:1;font-size:50px}.elementor-widget-text-editor .elementor-drop-cap-letter{display:inline-block}</style>
<p>Crime is everywhere, get a sidekick!</p>
<p>Join Chummies today and get the sidekick of your dreams.</p>
<p>Do you recognize a superhero when you look one in the face? Do you think such men and women truly exist? If not, then look. And think again.</p>
</div></div>

</div></div>
</div></section><section class="elementor-section elementor-top-section elementor-element elementor-element-bbecc07 elementor-section-content-middle elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-id="bbecc07" data-element_type="section" data-settings="{&quot;background_background&quot;:&quot;classic&quot;}"><div class="elementor-container elementor-column-gap-default">
<div class="elementor-column elementor-col-66 elementor-top-column elementor-element elementor-element-a856348" data-id="a856348" data-element_type="column"><div class="elementor-widget-wrap elementor-element-populated"><div class="elementor-element elementor-element-8b36f5a elementor-widget elementor-widget-text-editor" data-id="8b36f5a" data-element_type="widget" data-widget_type="text-editor.default"><div class="elementor-widget-container">
<h2>Hundreds of Heroes just like you are looking for a Heroic Connection.</h2>
<p>Everyday, heroes join Chummies to find heroic relationships. Chummies is the most open-minded community in the world.</p>
</div></div></div></div>
<div class="elementor-column elementor-col-33 elementor-top-column elementor-element elementor-element-99e9ee5" data-id="99e9ee5" data-element_type="column"><div class="elementor-widget-wrap elementor-element-populated"><div class="elementor-element elementor-element-ac30bbf elementor-widget elementor-widget-image" data-id="ac30bbf" data-element_type="widget" data-widget_type="image.default"><div class="elementor-widget-container"> <img decoding="async" width="300" height="588" src="/wp-content/blogs.dir/10/files/sites/14/2019/06/z-full.jpg" class="attachment-large size-large" alt="Z image" loading="lazy" sizes="(max-width: 300px) 100vw, 300px">
</div></div></div></div>
</div></section><section class="elementor-section elementor-top-section elementor-element elementor-element-a815d3b elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-id="a815d3b" data-element_type="section"><div class="elementor-container elementor-column-gap-default"><div class="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-5440e04" data-id="5440e04" data-element_type="column"><div class="elementor-widget-wrap elementor-element-populated"><div class="elementor-element elementor-element-75b8f04 elementor-widget elementor-widget-text-editor" data-id="75b8f04" data-element_type="widget" data-widget_type="text-editor.default"><div class="elementor-widget-container">
<h2>Discretion Matters</h2>
<p>We know you value your privacy, and we do too. We will never ask you to log in using a public social network account, and we have several features designed to help you keep your private life private- what ever the reason.</p>
</div></div></div></div></div></section><section class="elementor-section elementor-top-section elementor-element elementor-element-e520538 elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-id="e520538" data-element_type="section"><div class="elementor-container elementor-column-gap-default">
<div class="elementor-column elementor-col-25 elementor-top-column elementor-element elementor-element-cd5d11b" data-id="cd5d11b" data-element_type="column"><div class="elementor-widget-wrap elementor-element-populated"><div class="elementor-element elementor-element-fa8e9b7 elementor-widget elementor-widget-image" data-id="fa8e9b7" data-element_type="widget" data-widget_type="image.default"><div class="elementor-widget-container"> <img decoding="async" width="366" height="366" src="/wp-content/blogs.dir/10/files/sites/14/2019/06/RLSH-Coin.png" class="attachment-full size-full" alt="RLSH Coin" loading="lazy" sizes="(max-width: 366px) 100vw, 366px">
</div></div></div></div>
<div class="elementor-column elementor-col-25 elementor-top-column elementor-element elementor-element-ea325ee" data-id="ea325ee" data-element_type="column"><div class="elementor-widget-wrap elementor-element-populated"><div class="elementor-element elementor-element-e1cfcdc elementor-widget elementor-widget-text-editor" data-id="e1cfcdc" data-element_type="widget" data-widget_type="text-editor.default"><div class="elementor-widget-container">
<h4>Completely Independent</h4>
<p>You don&#8217;t need to link your Chummies account to any other social network. In fact, you can&#8217;t. instead use a private email address (for even more discretion, we recommend using a unique email just for this account).</p>
</div></div></div></div>
<div class="elementor-column elementor-col-25 elementor-top-column elementor-element elementor-element-2fb3ce4" data-id="2fb3ce4" data-element_type="column"><div class="elementor-widget-wrap elementor-element-populated"><div class="elementor-element elementor-element-5780f92 elementor-widget elementor-widget-image" data-id="5780f92" data-element_type="widget" data-widget_type="image.default"><div class="elementor-widget-container"> <img decoding="async" width="366" height="366" src="/wp-content/blogs.dir/10/files/sites/14/2019/06/RLSH-Coin.png" class="attachment-full size-full" alt="RLSH Coin" loading="lazy" sizes="(max-width: 366px) 100vw, 366px">
</div></div></div></div>
<div class="elementor-column elementor-col-25 elementor-top-column elementor-element elementor-element-b130779" data-id="b130779" data-element_type="column"><div class="elementor-widget-wrap elementor-element-populated"><div class="elementor-element elementor-element-dc0416f elementor-widget elementor-widget-text-editor" data-id="dc0416f" data-element_type="widget" data-widget_type="text-editor.default"><div class="elementor-widget-container">
<h4>Discreet Photos</h4>
<p>You control exactly what you want people to see! If you&#8217;re looking to add a bit more of an air of mystery, you can use our blur or mask tools. For even more discretion, you can mark photos as private and only share those with heroes who catch your eye.</p>
</div></div></div></div>
</div></section><section class="elementor-section elementor-top-section elementor-element elementor-element-a3093ae elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-id="a3093ae" data-element_type="section"><div class="elementor-container elementor-column-gap-default">
<div class="elementor-column elementor-col-25 elementor-top-column elementor-element elementor-element-095c078" data-id="095c078" data-element_type="column"><div class="elementor-widget-wrap elementor-element-populated"><div class="elementor-element elementor-element-568063f elementor-widget elementor-widget-image" data-id="568063f" data-element_type="widget" data-widget_type="image.default"><div class="elementor-widget-container"> <img decoding="async" width="366" height="366" src="/wp-content/blogs.dir/10/files/sites/14/2019/06/RLSH-Coin.png" class="attachment-full size-full" alt="RLSH Coin" loading="lazy" sizes="(max-width: 366px) 100vw, 366px">
</div></div></div></div>
<div class="elementor-column elementor-col-25 elementor-top-column elementor-element elementor-element-b0851d2" data-id="b0851d2" data-element_type="column"><div class="elementor-widget-wrap elementor-element-populated"><div class="elementor-element elementor-element-507d055 elementor-widget elementor-widget-text-editor" data-id="507d055" data-element_type="widget" data-widget_type="text-editor.default"><div class="elementor-widget-container">
<h4>Inbox Control</h4>
<p>We know sometimes it can be daunting to see an inbox full of messages. We help you manager your time and your connections with our Quick Reply feature. If you have too many winks or favorites, you can quickly and easily let those members know you&#8217;d be happy to respond to a full message.</p>
</div></div></div></div>
<div class="elementor-column elementor-col-25 elementor-top-column elementor-element elementor-element-83aa8c6" data-id="83aa8c6" data-element_type="column"><div class="elementor-widget-wrap elementor-element-populated"><div class="elementor-element elementor-element-ce9f772 elementor-widget elementor-widget-image" data-id="ce9f772" data-element_type="widget" data-widget_type="image.default"><div class="elementor-widget-container"> <img decoding="async" width="366" height="366" src="/wp-content/blogs.dir/10/files/sites/14/2019/06/RLSH-Coin.png" class="attachment-full size-full" alt="RLSH Coin" loading="lazy" sizes="(max-width: 366px) 100vw, 366px">
</div></div></div></div>
<div class="elementor-column elementor-col-25 elementor-top-column elementor-element elementor-element-3abc54c" data-id="3abc54c" data-element_type="column"><div class="elementor-widget-wrap elementor-element-populated"><div class="elementor-element elementor-element-952e80c elementor-widget elementor-widget-text-editor" data-id="952e80c" data-element_type="widget" data-widget_type="text-editor.default"><div class="elementor-widget-container">
<h4>Heroes Meet-up</h4>
<p>The excitement of traviling to a new city can be amplified when it includes meeting a new hero or team. With Traveling Heroes and Traveling Heroines features, you can find those connections before you&#8217;ve even packed your bags. Message members in your destination city ahead of time.</p>
</div></div></div></div>
</div></section><section class="elementor-section elementor-top-section elementor-element elementor-element-5de3be5 elementor-section-content-middle elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-id="5de3be5" data-element_type="section" data-settings="{&quot;background_background&quot;:&quot;classic&quot;}"><div class="elementor-container elementor-column-gap-default">
<div class="elementor-column elementor-col-33 elementor-top-column elementor-element elementor-element-7e2ef0b" data-id="7e2ef0b" data-element_type="column"><div class="elementor-widget-wrap elementor-element-populated"><div class="elementor-element elementor-element-ae44d90 elementor-widget elementor-widget-image" data-id="ae44d90" data-element_type="widget" data-widget_type="image.default"><div class="elementor-widget-container"> <img decoding="async" width="767" height="1023" src="/wp-content/blogs.dir/10/files/sites/14/2019/06/razorhawk-portrait.jpg" class="attachment-large size-large" alt="Razor Hawk" loading="lazy" sizes="(max-width: 767px) 100vw, 767px">
</div></div></div></div>
<div class="elementor-column elementor-col-66 elementor-top-column elementor-element elementor-element-79d64f7" data-id="79d64f7" data-element_type="column"><div class="elementor-widget-wrap elementor-element-populated"><div class="elementor-element elementor-element-091903e elementor-widget elementor-widget-text-editor" data-id="091903e" data-element_type="widget" data-widget_type="text-editor.default"><div class="elementor-widget-container">
<h2>It only takes a moment</h2>
<p>Its all too easy to get caught up in the patrol. We count the hours instead of fighting crime and we long for something more., but in the end we are left with the mundane, boring, everyday activities that make up our lives.</p>
<p>Once in a while, something special happens. An arm robbery, a raging fire, a broken down care; these moments show us a glimpse of something different, something more. We think about them and what they could mean for us, the path not taken and the life not lived.</p>
</div></div></div></div>
</div></section><section class="elementor-section elementor-top-section elementor-element elementor-element-d208a3d elementor-section-content-middle elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-id="d208a3d" data-element_type="section"><div class="elementor-container elementor-column-gap-default">
<div class="elementor-column elementor-col-66 elementor-top-column elementor-element elementor-element-12c0f5d" data-id="12c0f5d" data-element_type="column"><div class="elementor-widget-wrap elementor-element-populated"><div class="elementor-element elementor-element-e8d4f59 elementor-widget elementor-widget-text-editor" data-id="e8d4f59" data-element_type="widget" data-widget_type="text-editor.default"><div class="elementor-widget-container">
<h2>Chummies is for every Hero</h2>
<p>Whatever bringers you to Chummies, you can feel safe knowing that you&#8217;re not alone. Our members are heroes, citizen activists, and hero supporters seeking a partnership. They are looking to make a different. Every hero has different reasons for joining a site like Chummies. No matter your reason, circumstances, or what you&#8217;re looking for, you&#8217;ll find what&#8217;s missing at Chummies.</p>
</div></div></div></div>
<div class="elementor-column elementor-col-33 elementor-top-column elementor-element elementor-element-efac53f" data-id="efac53f" data-element_type="column"><div class="elementor-widget-wrap elementor-element-populated"><div class="elementor-element elementor-element-1efc1a8 elementor-widget elementor-widget-image" data-id="1efc1a8" data-element_type="widget" data-widget_type="image.default"><div class="elementor-widget-container"> <img decoding="async" width="694" height="1023" src="/wp-content/blogs.dir/10/files/sites/14/2019/06/civitronposter.jpg" class="attachment-large size-large" alt="Civitron" loading="lazy" sizes="(max-width: 694px) 100vw, 694px">
</div></div></div></div>
</div></section><section class="elementor-section elementor-top-section elementor-element elementor-element-9780241 elementor-section-content-middle elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-id="9780241" data-element_type="section" data-settings="{&quot;background_background&quot;:&quot;classic&quot;}"><div class="elementor-container elementor-column-gap-default">
<div class="elementor-column elementor-col-33 elementor-top-column elementor-element elementor-element-debc1a7" data-id="debc1a7" data-element_type="column"><div class="elementor-widget-wrap elementor-element-populated"><div class="elementor-element elementor-element-fe461af elementor-widget elementor-widget-image" data-id="fe461af" data-element_type="widget" data-widget_type="image.default"><div class="elementor-widget-container"> <img decoding="async" width="691" height="1023" src="/wp-content/blogs.dir/10/files/sites/14/2019/06/zimmerposter.jpg" class="attachment-large size-large" alt="Zimmer Poster" loading="lazy" sizes="(max-width: 691px) 100vw, 691px">
</div></div></div></div>
<div class="elementor-column elementor-col-66 elementor-top-column elementor-element elementor-element-2b3ee6b" data-id="2b3ee6b" data-element_type="column"><div class="elementor-widget-wrap elementor-element-populated"><div class="elementor-element elementor-element-c203774 elementor-widget elementor-widget-text-editor" data-id="c203774" data-element_type="widget" data-widget_type="text-editor.default"><div class="elementor-widget-container"><p>When Chummies started, there weren&#8217;t many places heroes could go for support. Meeting a hero on the streets or through forums is too risky when discretion is your number one concern. Many turned to traditional websites, but found it difficult to connect with heroes looking for similar types of methods. And so Chummies was created as the first website that was open and honest about what you could find there, Like-minded heroes looking for partnerships. Chummies revolve around the idea that heroes should be able to do whatever they want in their cities. What began soon grew into an international leader in hero meet-ups.</p></div></div></div></div>
</div></section><section class="elementor-section elementor-top-section elementor-element elementor-element-5a8c2a0 elementor-section-stretched elementor-section-full_width elementor-section-height-min-height elementor-section-content-top elementor-section-height-default elementor-section-items-middle" data-id="5a8c2a0" data-element_type="section" data-settings="{&quot;stretch_section&quot;:&quot;section-stretched&quot;,&quot;background_background&quot;:&quot;classic&quot;}"><div class="elementor-container elementor-column-gap-default"><div class="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-fe91143" data-id="fe91143" data-element_type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;}"><div class="elementor-widget-wrap"></div></div></div></section>
</div>
<footer id="footer" class="clearfix site-footer" ><div class="footer-bar grid col-940"><div class="content-outer container"><div class="row"><div class="footer-layouts copyright"> <span class="copyright_icon_and_year"> &copy;  2022 </span> iHero Apps. All Rights Reserved. 
</div></div></div></div></footer>
</div> 
</body>
</html>